# Generated by Django 4.1.7 on 2023-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehours',
            name='store_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='store_id',
            field=models.CharField(max_length=100),
        ),
    ]
