# Generated by Django 4.1.7 on 2023-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_storehours_store_id_alter_storestatus_store_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehours',
            name='store_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storetimezone',
            name='store_id',
            field=models.IntegerField(),
        ),
    ]
