# Generated by Django 4.1.7 on 2023-04-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.BigIntegerField()),
                ('status', models.CharField(max_length=8)),
                ('uptime_last_hour', models.FloatField(default=None)),
                ('downtime_last_hour', models.FloatField(default=None)),
                ('uptime_last_day', models.FloatField(default=None)),
                ('downtime_last_day', models.FloatField(default=None)),
                ('uptime_last_week', models.FloatField(default=None)),
                ('downtime_last_week', models.FloatField(default=None)),
            ],
        ),
    ]
